version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      npm-patch-minor:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
